closes #204 204/google workspace credentials k8s fix
1Password/scim-examples pull request #205
Opened 2022-09-15 19:27 UTC by scottisloud

This PR updates the Kubernetes example deployment to support providing Google Workspace credentials at deployment time, or updating an existing bridge with Workspace credentials. 

The deployment now correctly mounts workspace secrets if they are created. 

* Refactored `volumeMounts` and `volumes` in op-scim-deployment to use a projected volume to accommodate multiple secrets. 
* Workspace secrets are marked as optional so a op-scim-bridge container will be deployed even if these secrets are not present. 
* Updated `kubectl create secret` command to include a key value for Workspace secrets, in line with what has been done for the `scimession` secret previously, to avoid naming discrepancies. 

In my testing, this deployment will work with or without Workspace credentials. It also works to update an existing bridge to have Workspace credentials (an unlikely scenario but 🤷‍♂️ ).

2022-09-15 19:35 UTC, scottisloud commented
closes #204

2022-09-15 21:14 UTC, ag-adampike requested changes
This is great work, but needs one small change to the `kubectl create secret` commands in order for the Secrets to be mounted with the `.json` extension intact.

2022-09-15 21:14 UTC, ag-adampike commented on kubernetes/README.md
> +kubectl create secret generic workspace-credentials --from-file=workspace-credentials=/path/to/<keyfile>.json
```suggestion
kubectl create secret generic workspace-credentials --from-file=workspace-credentials.json=./workspace-credentials.json
// Replace `./workspace-credentials.json` with `[path/]filename.json` if saved elsewhere or with a different filename
```

2022-09-15 21:14 UTC, ag-adampike commented on kubernetes/op-scim-deployment.yaml
> +            - name: secrets
```suggestion
            - name: secret
```

Given the value for this is an arbitrary label, perhaps we should consider changing this to match the directory name.

2022-09-15 21:14 UTC, ag-adampike commented on kubernetes/op-scim-deployment.yaml
> +      - name: secrets
```suggestion
      - name: secret
```

2022-09-15 21:15 UTC, scottisloud commented on kubernetes/README.md
> +kubectl create secret generic workspace-settings --from-file=workspace-settings=/path/to/workspace-settings.json
.json is not needed on the keyname in my testing.

2022-09-15 23:23 UTC, scottisloud commented
Integrated and tested Pike's suggestions and updated the readme with a brief note about potential ignorable errors a person may get when storing their workspace json files in the same directory as the deployment.

2022-09-15 23:25 UTC, ag-adampike submitted a review, later dismissed
LGTM!!:tada:

2022-09-15 23:35 UTC, scottisloud commented
Apparently Git wasn't signing my commits 😫 
Working on figuring out why that's the case.

2022-09-16 00:17 UTC, scottisloud commented
Phew, after a harrowing rebase I've managed to get all previous commits signed.

2022-09-16 00:43 UTC, ag-adampike approved these changes

2022-09-16 17:50 UTC, black-bryan commented
Successfully tested K8 deployment with workspace-settings and workspace-credentials supplied as K8 secrets, as well as non GW bridge deployment.

2022-09-19 13:20 UTC, chasdl approved these changes
These changes look solid to me, appreciate the effort here!

2022-09-19 14:04 UTC, merged