Azure Container Apps Deployment Improvements
1Password/scim-examples pull request #270
Opened 2023-12-05 14:57 UTC by black-bryan

Overall improvements to the Azure Container App deployment guide.

* Adding support for deploying the 1Password SCIM Bridge to Azure Container apps using a YAML file. 
  * Prioritizing the `yaml` deployment over the `az containerapp create` commands for separate containers. 
  * Keeping the commands available in the guide for anybody who wants to still created based off the commands.
* Shortening environment variable names to simply and shorten commands used during deployment
* Clarity on some administrative steps.
* Adding `--enable-workload-profiles false` to the `az containerapp env create` command to accommodate the [change made by Azure on December 5th version 2.55.0](https://learn.microsoft.com/en-us/cli/azure/release-notes-azure-cli#containerapp-1) in the AZ CLI tooling.

2023-12-05 16:56 UTC, black-bryan commented on beta/azure-container-apps/ReadMe.md
> +    > **Note:** The ConAppName can contain lowercase letters, numerals, and hyphens. It must be between 2 and 32 characters long, and cannot start or end with a hyphen.
Tested during a call today, and found it also does not support starting with a number for the Container App Name
```suggestion
    > **Note:** The ConAppName variable (Container App Name) can contain lowercase letters, numerals, and hyphens. It must be between 2 and 32 characters long, and cannot start or end with a hyphen or cannot start with a number.
```

2023-12-05 22:59 UTC, plttn requested changes
Again, minor changes.

2023-12-05 22:59 UTC, plttn commented on beta/azure-container-apps/ReadMe.md
> +    - Find the `aca.op-scim-bridge.yaml` file that you saved to your computer and choose it.
We could potentially have them curl the yaml down, save an upload/download step?

2023-12-05 22:59 UTC, plttn commented on beta/azure-container-apps/ReadMe.md
> +10. Open the domain name listed in a separate browser tab to test your connection. You can sign in to your SCIM bridge using your bearer token.
I've ran into this enough times, can we specify "https://foobar" here? I've had to tell folks "go ahead and put https:// ahead of it"

2023-12-06 16:39 UTC, plttn approved these changes
Looks good to me, I haven't had a chance to do a test deployment from Windows yet however, so I'll count this as a half-approval.

2023-12-07 12:18 UTC, black-bryan commented
@scottisloud, my guess is the fact that the `curl` command or `Invoke-RestMethod -Uri` command are now pointing to the path where the .yaml will live when this is merged caused you the issue. Sorry I should have called this out as part of the review notes.
As it does not look like there are any "real" containers created in your Container App. You can test with `curl https://raw.githubusercontent.com/1Password/scim-examples/solutions/bb/aca-yaml/beta/azure-container-apps/aca-op-scim-bridge.yaml --output aca-op-scim-bridge.yaml --silent` for and repeat the other command in step #9.

2023-12-07 20:03 UTC, merged