Ag dayton/readme changes
1Password/scim-examples pull request #322
Opened 2024-07-26 16:36 UTC by AG-Dayton

2024-07-26 16:37 UTC, AG-Dayton commented
Added some further delineation to the GW-specific steps in the compose manual deployment steps. 😄

2024-07-26 23:20 UTC, ag-rdoucette requested changes
Hi Dayton, 

Can you check link 222, formatting seems to be incorrect.

2024-07-30 13:41 UTC, AG-Dayton commented
> Hi Dayton,
> 
> Can you check line 222, formatting seems to be incorrect.

Should be fixed up now!

2024-07-30 15:01 UTC, ag-rdoucette approved these changes

2024-08-02 20:20 UTC, merged